
DROP TABLE IF EXISTS data;

CREATE TABLE data (c1   STRING,
    c2    STRING,
    C3 INTEGER
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';

LOAD DATA LOCAL INPATH "data.tsv" OVERWRITE INTO TABLE data;

INSERT OVERWRITE DIRECTORY '/tmp/output'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT c1,c2,c3 FROM data ORDER BY c1,c3,c2;

!hadoop fs -copyToLocal /tmp/output output
